kiali:
  enabled: true
  createDemoSecret: true
  contextPath: /
  dashboard:
    grafanaURL: http://grafana-istio.eni.yannig.ovh
    jaegerURL:  http://jaeger.eni.yannig.ovh

  ingress:
    enabled: true
    hosts:
      - "kiali.eni.yannig.ovh"
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kiali-eni-yannig-ovh
