global:
  sds:
    enabled: true

  k8sIngress:
    enabled: true
    enableHttps: true
    gatewayName: ingressgateway

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true

gateways:
  istio-ingressgateway:
    sds:
      enabled: true

mixer:
  policy:
    enabled: true

  telemetry:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
