gateways:
  istio-ingressgateway:
    sds:
      enabled: true

global:
  sds:
    enabled: true

  k8sIngress:
    enabled: true
    enableHttps: true
    gatewayName: ingressgateway

grafana:
  enabled: true

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true

tracing:
  enabled: true

kiali:
  enabled: true
  createDemoSecret: true
  contextPath: /
  dashboard:
    grafanaURL: http://grafana-istio.eni.yannig.ovh
    jaegerURL:  http://jaeger.eni.yannig.ovh

mixer:
  policy:
    enabled: true

  telemetry:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
