kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-pods-global
subjects:
  - kind: User
    name: admin
    namespace: delegation
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pods-read-clusterrole
  apiGroup: rbac.authorization.k8s.io
