apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mailhog
spec:
  rules:
  - host: "mailhog.eni.yannig.ovh"
    http:
      paths:
      - path: /
        backend:
          serviceName: mailhog
          servicePort: 8025
