apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-hunter
spec:
  schedule: "0 12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: kube-hunter
            image: aquasec/kube-hunter 
            command: ["python", "kube-hunter.py"]
            args:
              - "--pod"
              - "--token"
              - "eyJ0e...kU4jE0"
          restartPolicy: Never
      backoffLimit: 4
