apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-cluster-secret
  minAvailable: 1
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
type: Opaque
data:
  # not-so-secure
  ROOT_PASSWORD: bm90LXNvLXNlY3VyZQ==
  # my-user
  USER: bXktdXNlcg==
  # my-password
  PASSWORD: bXktcGFzc3dvcmQ=
  # my-db
  DATABASE: bXktZGI=
