# apiVersion: certmanager.k8s.io/v1alpha1 (version < 0.11)
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: eni-yannig-ovh
spec:
  secretName: eni-yannig-ovh-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "eni.yannig.ovh"
  dnsNames:
    - "eni.yannig.ovh"
    - "*.eni.yannig.ovh"
  acme:
    config:
      - dns01:
          provider: prod-dns
        domains:
          - "eni.yannig.ovh"
          - "*.eni.yannig.ovh"
