apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-updater
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-updater
  namespace: develop
rules:
- apiGroups: ["extensions"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jenkins-updater-binding
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-updater
subjects:
  - kind: ServiceAccount
    name: jenkins-updater
    namespace: jenkins
