# apiVersion: certmanager.k8s.io/v1alpha1 (version < 0.11)
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: eni-yannig-ovh
  namespace: istio-system
spec:
  secretName: test-eni-yannig-ovh-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "eni.yannig.ovh"
  dnsNames:
    - "eni.yannig.ovh"
    - "*.eni.yannig.ovh"
  acme:
    config:
      - http01:
          ingressClass: istio
        domains:
          - "eni.yannig.ovh"
          - "*.eni.yannig.ovh"
