apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: eni-yannig-ovh
spec:
  secretName: eni-yannig-ovh-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "eni.yannig.ovh"
  dnsNames:
    - "eni.yannig.ovh"
    - "*.eni.yannig.ovh"
  acme:
    config:
      - dns01:
          provider: staging-dns
        domains:
          - "eni.yannig.ovh"
          - "*.eni.yannig.ovh"
