apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mailhog-gateway
  namespace: test-istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - "test.eni.yannig.ovh"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "test.eni.yannig.ovh"
      tls:
        mode: SIMPLE
        credentialName: "test-eni-yannig-ovh-prod-tls"
